server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoDB?createDatabaseIfNotExist=true
    username: root
    password: rootpass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true